### PR TITLE
Attribute allegiance abilities to subFaction

### PR DESCRIPTION
**Pull request by exonian**
Standing on the shoulders of giants for the tests 😁

### CODE REVIEW

**Comment by exonian** [comment]
Fixes #1184

**Comment by daviseford** [comment]
What happens if there is no subfaction, or if the subfaction isn't applying the rules? I guess by convention we've named all of our solo subfactions the same as a faction

**Comment by exonian** [comment]
Your Sylvaneth test already covers this case to an extent
But yeah, the solo subfaction is set when the faction is selected (it's `subFactions[0]`) so one should always be present
I didn't check beyond Sylvaneth for the naming of them tbh

**Comment by exonian** [comment]
"or if the subfaction isn't applying the rules"
I had in my mind that this was a thing, but now no longer think it is.

Is there a situation where an effect comes straight from the Faction and not the SubFaction, other than when it's a solo SubFaction? As far as I could think, everything is either SubFaction effects or it's via selections (artifacts, spells etc) or Flavors anyway

**Comment by daviseford** [comment]
you are correct

**Pull request merged**
